[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
intentfi = "7opSCrXjWAC5cjMdSJiFjHGY2ncWiyQyHZEbmjiUA3Ax"

[programs.localnet]
intentfi = "7opSCrXjWAC5cjMdSJiFjHGY2ncWiyQyHZEbmjiUA3Ax"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
